services:
    subtitle-transformer:
        container_name: ${PROJECT_NAME}-subtitle-transformer
        env_file:
            - .env.local
        build:
            dockerfile: ./Dockerfile
            args:
                SERVICE_PORT: 5000
                SERVICE_NAME: subtitle-transformer
        restart: unless-stopped
        networks:
            - api_network
        volumes:
            - ./:/app
        command: celery -A src.main.celery worker --loglevel=info --queues=api_to_subtitle_transformer
        ports:
            - "5003:5000"

networks:
  api_network:
    name: api_network
    driver: bridge
